import type { NextConfig } from "next";
import { withPayload } from "@payloadcms/next/withPayload";

const nextConfig: NextConfig = {
  reactCompiler: true,
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'cryospaclinics.com.au',
      },
    ],
  },
  async redirects() {
    return [
      // Static pages
      { source: "/pricing-3", destination: "/pricing", permanent: true },
      { source: "/pricing-3/", destination: "/pricing", permanent: true },
      { source: "/blogs", destination: "/blog", permanent: true },
      { source: "/blogs/", destination: "/blog", permanent: true },

      // Testimonials (catch-all)
      { source: "/wp_testimonial", destination: "/testimonials", permanent: true },
      { source: "/wp_testimonial/", destination: "/testimonials", permanent: true },
      { source: "/testimonial/:slug", destination: "/testimonials", permanent: true },

      // Service pages (old root paths -> /services/:slug)
      { source: "/services/cryotherapy", destination: "/services", permanent: true },
      { source: "/services/cryotherapy/", destination: "/services", permanent: true },
      { source: "/facials", destination: "/services/facials", permanent: true },
      { source: "/facials/", destination: "/services/facials", permanent: true },
      { source: "/massage", destination: "/services/massage", permanent: true },
      { source: "/massage/", destination: "/services/massage", permanent: true },
      { source: "/contrast-therapy", destination: "/services/contrast-therapy", permanent: true },
      { source: "/contrast-therapy/", destination: "/services/contrast-therapy", permanent: true },
      { source: "/salt-room-sydney", destination: "/services/salt-room-sydney", permanent: true },
      { source: "/salt-room-sydney/", destination: "/services/salt-room-sydney", permanent: true },
      { source: "/lymphatic-drainage-massage-crows-nest", destination: "/services/lymphatic-drainage-massage-crows-nest", permanent: true },
      { source: "/lymphatic-drainage-massage-crows-nest/", destination: "/services/lymphatic-drainage-massage-crows-nest", permanent: true },
      { source: "/revitalise-your-body-and-mind-with-our-exclusive-30-minute-sauna-session", destination: "/services/infrared-sauna", permanent: true },
      { source: "/revitalise-your-body-and-mind-with-our-exclusive-30-minute-sauna-session/", destination: "/services/infrared-sauna", permanent: true },
      { source: "/experience-ultimate-relaxation-and-wellness", destination: "/services/infrared-sauna", permanent: true },
      { source: "/experience-ultimate-relaxation-and-wellness/", destination: "/services/infrared-sauna", permanent: true },
      { source: "/wholebody-cryo-2", destination: "/services/wholebody-cryo", permanent: true },
      { source: "/wholebody-cryo-2/", destination: "/services/wholebody-cryo", permanent: true },
      { source: "/infrared-sauna", destination: "/services/infrared-sauna", permanent: true },
      { source: "/infrared-sauna/", destination: "/services/infrared-sauna", permanent: true },
      { source: "/elevate", destination: "/services/elevate", permanent: true },
      { source: "/elevate/", destination: "/services/elevate", permanent: true },
      { source: "/special-offers-1121", destination: "/blog", permanent: true },
      { source: "/special-offers-1121/", destination: "/blog", permanent: true },
      { source: "/red-light-therapy", destination: "/services/red-light-therapy", permanent: true },
      { source: "/red-light-therapy/", destination: "/services/red-light-therapy", permanent: true },
      { source: "/norma-tec-compression-boots", destination: "/services/norma-tec-compression-boots", permanent: true },
      { source: "/norma-tec-compression-boots/", destination: "/services/norma-tec-compression-boots", permanent: true },
      { source: "/biohack", destination: "/services/biohack", permanent: true },
      { source: "/biohack/", destination: "/services/biohack", permanent: true },
      { source: "/immune", destination: "/services/immune", permanent: true },
      { source: "/immune/", destination: "/services/immune", permanent: true },
      { source: "/16853-2", destination: "/", permanent: true },
      { source: "/16853-2/", destination: "/", permanent: true },
      { source: "/promotions", destination: "/blog", permanent: true },
      { source: "/promotions/", destination: "/blog", permanent: true },
      { source: "/chromotheraphy", destination: "/services/chromotheraphy", permanent: true },
      { source: "/chromotheraphy/", destination: "/services/chromotheraphy", permanent: true },
      { source: "/localised-cryo", destination: "/services/localised-cryo", permanent: true },
      { source: "/localised-cryo/", destination: "/services/localised-cryo", permanent: true },
      { source: "/dr-rhonda-patrick-cryotherapy", destination: "/blog/dr-rhonda-patrick-cryotherapy", permanent: true },
      { source: "/dr-rhonda-patrick-cryotherapy/", destination: "/blog/dr-rhonda-patrick-cryotherapy", permanent: true },

      // Blog posts (old root paths -> /blog/:slug)
      { source: "/unveiling-the-healing-power-of-infrared-saunas-in-sydney", destination: "/blog/unveiling-the-healing-power-of-infrared-saunas-in-sydney", permanent: true },
      { source: "/unveiling-the-healing-power-of-infrared-saunas-in-sydney/", destination: "/blog/unveiling-the-healing-power-of-infrared-saunas-in-sydney", permanent: true },
      { source: "/5-tips-to-enhance-your-infrared-sauna-session", destination: "/blog/5-tips-to-enhance-your-infrared-sauna-session", permanent: true },
      { source: "/5-tips-to-enhance-your-infrared-sauna-session/", destination: "/blog/5-tips-to-enhance-your-infrared-sauna-session", permanent: true },
      { source: "/what-happens-after-whole-body-cryotherapy", destination: "/blog/what-happens-after-whole-body-cryotherapy", permanent: true },
      { source: "/what-happens-after-whole-body-cryotherapy/", destination: "/blog/what-happens-after-whole-body-cryotherapy", permanent: true },
      { source: "/how-infrared-saunas-can-boost-your-immune-system", destination: "/blog/how-infrared-saunas-can-boost-your-immune-system", permanent: true },
      { source: "/how-infrared-saunas-can-boost-your-immune-system/", destination: "/blog/how-infrared-saunas-can-boost-your-immune-system", permanent: true },
      { source: "/how-regular-sauna-use-can-help-you-live-longer", destination: "/blog/how-regular-sauna-use-can-help-you-live-longer", permanent: true },
      { source: "/how-regular-sauna-use-can-help-you-live-longer/", destination: "/blog/how-regular-sauna-use-can-help-you-live-longer", permanent: true },
      { source: "/does-salt-room-therapy-help-with-acne", destination: "/blog/does-salt-room-therapy-help-with-acne", permanent: true },
      { source: "/does-salt-room-therapy-help-with-acne/", destination: "/blog/does-salt-room-therapy-help-with-acne", permanent: true },
      { source: "/red-light-therapy-effectiveness-for-skin-care", destination: "/blog/red-light-therapy-effectiveness-for-skin-care", permanent: true },
      { source: "/red-light-therapy-effectiveness-for-skin-care/", destination: "/blog/red-light-therapy-effectiveness-for-skin-care", permanent: true },
      { source: "/vasoconstriction-and-vasodilation-explained", destination: "/blog/vasoconstriction-and-vasodilation-explained", permanent: true },
      { source: "/vasoconstriction-and-vasodilation-explained/", destination: "/blog/vasoconstriction-and-vasodilation-explained", permanent: true },
      { source: "/the-paleo-diet-fad-or-friend", destination: "/blog/the-paleo-diet-fad-or-friend", permanent: true },
      { source: "/the-paleo-diet-fad-or-friend/", destination: "/blog/the-paleo-diet-fad-or-friend", permanent: true },
      { source: "/how-important-is-sleep-really-when-it-comes-to-living-a-strong-and-balanced-life-and-how-can-cryotherapy-in-australia-help", destination: "/blog/how-important-is-sleep-really-when-it-comes-to-living-a-strong-and-balanced-life-and-how-can-cryotherapy-in-australia-help", permanent: true },
      { source: "/how-important-is-sleep-really-when-it-comes-to-living-a-strong-and-balanced-life-and-how-can-cryotherapy-in-australia-help/", destination: "/blog/how-important-is-sleep-really-when-it-comes-to-living-a-strong-and-balanced-life-and-how-can-cryotherapy-in-australia-help", permanent: true },
      { source: "/contrast-therapy-what-is-it-and-why-its-beneficial", destination: "/blog/contrast-therapy-what-is-it-and-why-its-beneficial", permanent: true },
      { source: "/contrast-therapy-what-is-it-and-why-its-beneficial/", destination: "/blog/contrast-therapy-what-is-it-and-why-its-beneficial", permanent: true },
      { source: "/salt-therapy-everything-you-need-to-know", destination: "/blog/salt-therapy-everything-you-need-to-know", permanent: true },
      { source: "/salt-therapy-everything-you-need-to-know/", destination: "/blog/salt-therapy-everything-you-need-to-know", permanent: true },
      { source: "/how-do-normatec-compression-boots-work-for-recovery", destination: "/blog/how-do-normatec-compression-boots-work-for-recovery", permanent: true },
      { source: "/how-do-normatec-compression-boots-work-for-recovery/", destination: "/blog/how-do-normatec-compression-boots-work-for-recovery", permanent: true },
      { source: "/5-ice-bath-benefits-for-health-wellness-and-recovery", destination: "/blog/5-ice-bath-benefits-for-health-wellness-and-recovery", permanent: true },
      { source: "/5-ice-bath-benefits-for-health-wellness-and-recovery/", destination: "/blog/5-ice-bath-benefits-for-health-wellness-and-recovery", permanent: true },
      { source: "/is-an-infrared-sauna-better-than-a-regular-sauna", destination: "/blog/is-an-infrared-sauna-better-than-a-regular-sauna", permanent: true },
      { source: "/is-an-infrared-sauna-better-than-a-regular-sauna/", destination: "/blog/is-an-infrared-sauna-better-than-a-regular-sauna", permanent: true },
      { source: "/how-salt-therapy-can-help-with-acne", destination: "/blog/how-salt-therapy-can-help-with-acne", permanent: true },
      { source: "/how-salt-therapy-can-help-with-acne/", destination: "/blog/how-salt-therapy-can-help-with-acne", permanent: true },
      { source: "/hot-cold-salty-a-visit-to-cryospa-2", destination: "/blog/hot-cold-salty-a-visit-to-cryospa-2", permanent: true },
      { source: "/hot-cold-salty-a-visit-to-cryospa-2/", destination: "/blog/hot-cold-salty-a-visit-to-cryospa-2", permanent: true },
      { source: "/vitamin-iv", destination: "/blog/vitamin-iv", permanent: true },
      { source: "/vitamin-iv/", destination: "/blog/vitamin-iv", permanent: true },
      { source: "/what-is-red-light-therapy", destination: "/blog/what-is-red-light-therapy", permanent: true },
      { source: "/what-is-red-light-therapy/", destination: "/blog/what-is-red-light-therapy", permanent: true },
      { source: "/infrared-saunas-how-hot-do-they-really-get", destination: "/blog/infrared-saunas-how-hot-do-they-really-get", permanent: true },
      { source: "/infrared-saunas-how-hot-do-they-really-get/", destination: "/blog/infrared-saunas-how-hot-do-they-really-get", permanent: true },
      { source: "/can-cryotherapy-help-you-lose-weight", destination: "/blog/can-cryotherapy-help-you-lose-weight", permanent: true },
      { source: "/can-cryotherapy-help-you-lose-weight/", destination: "/blog/can-cryotherapy-help-you-lose-weight", permanent: true },
      { source: "/how-normatec-compression-therapy-can-help-you", destination: "/blog/how-normatec-compression-therapy-can-help-you", permanent: true },
      { source: "/how-normatec-compression-therapy-can-help-you/", destination: "/blog/how-normatec-compression-therapy-can-help-you", permanent: true },
      { source: "/how-infrared-sauna-use-can-help-depression-and-anxiety", destination: "/blog/how-infrared-sauna-use-can-help-depression-and-anxiety", permanent: true },
      { source: "/how-infrared-sauna-use-can-help-depression-and-anxiety/", destination: "/blog/how-infrared-sauna-use-can-help-depression-and-anxiety", permanent: true },
      { source: "/suffering-from-acne-heres-how-our-salt-room-can-help", destination: "/blog/suffering-from-acne-heres-how-our-salt-room-can-help", permanent: true },
      { source: "/suffering-from-acne-heres-how-our-salt-room-can-help/", destination: "/blog/suffering-from-acne-heres-how-our-salt-room-can-help", permanent: true },
      { source: "/pain-management-here-are-4-ways-we-can-help", destination: "/blog/pain-management-here-are-4-ways-we-can-help", permanent: true },
      { source: "/pain-management-here-are-4-ways-we-can-help/", destination: "/blog/pain-management-here-are-4-ways-we-can-help", permanent: true },
      { source: "/vitamin-d-deficiency-what-causes-it-and-how-to-prevent-it", destination: "/blog/vitamin-d-deficiency-what-causes-it-and-how-to-prevent-it", permanent: true },
      { source: "/vitamin-d-deficiency-what-causes-it-and-how-to-prevent-it/", destination: "/blog/vitamin-d-deficiency-what-causes-it-and-how-to-prevent-it", permanent: true },
      { source: "/what-causes-inflammation-and-how-can-i-prevent-it", destination: "/blog/what-causes-inflammation-and-how-can-i-prevent-it", permanent: true },
      { source: "/what-causes-inflammation-and-how-can-i-prevent-it/", destination: "/blog/what-causes-inflammation-and-how-can-i-prevent-it", permanent: true },
      { source: "/cryotherapy-and-athletes-the-perfect-match", destination: "/blog/cryotherapy-and-athletes-the-perfect-match", permanent: true },
      { source: "/cryotherapy-and-athletes-the-perfect-match/", destination: "/blog/cryotherapy-and-athletes-the-perfect-match", permanent: true },
      { source: "/are-hot-baths-beneficial", destination: "/blog/are-hot-baths-beneficial", permanent: true },
      { source: "/are-hot-baths-beneficial/", destination: "/blog/are-hot-baths-beneficial", permanent: true },
      { source: "/are-cold-showers-beneficial", destination: "/blog/are-cold-showers-beneficial", permanent: true },
      { source: "/are-cold-showers-beneficial/", destination: "/blog/are-cold-showers-beneficial", permanent: true },
      { source: "/chromotherapy-what-is-it-and-how-can-it-help", destination: "/blog/chromotherapy-what-is-it-and-how-can-it-help", permanent: true },
      { source: "/chromotherapy-what-is-it-and-how-can-it-help/", destination: "/blog/chromotherapy-what-is-it-and-how-can-it-help", permanent: true },
      { source: "/what-are-the-benefits-of-salt-room-therapy", destination: "/blog/what-are-the-benefits-of-salt-room-therapy", permanent: true },
      { source: "/what-are-the-benefits-of-salt-room-therapy/", destination: "/blog/what-are-the-benefits-of-salt-room-therapy", permanent: true },
      { source: "/how-white-blood-cells-impact-immune-system", destination: "/blog/how-white-blood-cells-impact-immune-system", permanent: true },
      { source: "/how-white-blood-cells-impact-immune-system/", destination: "/blog/how-white-blood-cells-impact-immune-system", permanent: true },
      { source: "/the-science-behind-the-ketogenic-diet-and-why-it-may-be-beneficial-for-you", destination: "/blog/the-science-behind-the-ketogenic-diet-and-why-it-may-be-beneficial-for-you", permanent: true },
      { source: "/the-science-behind-the-ketogenic-diet-and-why-it-may-be-beneficial-for-you/", destination: "/blog/the-science-behind-the-ketogenic-diet-and-why-it-may-be-beneficial-for-you", permanent: true },
      { source: "/why-you-need-to-add-bentonite-clay-to-your-wellness-routine", destination: "/blog/why-you-need-to-add-bentonite-clay-to-your-wellness-routine", permanent: true },
      { source: "/why-you-need-to-add-bentonite-clay-to-your-wellness-routine/", destination: "/blog/why-you-need-to-add-bentonite-clay-to-your-wellness-routine", permanent: true },
      { source: "/chroma", destination: "/blog/chroma", permanent: true },
      { source: "/chroma/", destination: "/blog/chroma", permanent: true },
      { source: "/whole-body-the-importance-of-sleep-and-steps-you-can-take-to-increase-the-quality-of-your-shut-eye", destination: "/blog/whole-body-the-importance-of-sleep-and-steps-you-can-take-to-increase-the-quality-of-your-shut-eye", permanent: true },
      { source: "/whole-body-the-importance-of-sleep-and-steps-you-can-take-to-increase-the-quality-of-your-shut-eye/", destination: "/blog/whole-body-the-importance-of-sleep-and-steps-you-can-take-to-increase-the-quality-of-your-shut-eye", permanent: true },
      { source: "/how-regular-sauna-usage-may-aid-in-reducing-the-risk-of-a-cardiac-event", destination: "/blog/how-regular-sauna-usage-may-aid-in-reducing-the-risk-of-a-cardiac-event", permanent: true },
      { source: "/how-regular-sauna-usage-may-aid-in-reducing-the-risk-of-a-cardiac-event/", destination: "/blog/how-regular-sauna-usage-may-aid-in-reducing-the-risk-of-a-cardiac-event", permanent: true },
      { source: "/how-the-wim-hof-method-can-help-prepare-you-for-a-cryotherapy-chamber", destination: "/blog/how-the-wim-hof-method-can-help-prepare-you-for-a-cryotherapy-chamber", permanent: true },
      { source: "/how-the-wim-hof-method-can-help-prepare-you-for-a-cryotherapy-chamber/", destination: "/blog/how-the-wim-hof-method-can-help-prepare-you-for-a-cryotherapy-chamber", permanent: true },
      { source: "/how-to-know-when-it-may-be-time-to-look-into-cryotherapy-for-athletes", destination: "/blog/how-to-know-when-it-may-be-time-to-look-into-cryotherapy-for-athletes", permanent: true },
      { source: "/how-to-know-when-it-may-be-time-to-look-into-cryotherapy-for-athletes/", destination: "/blog/how-to-know-when-it-may-be-time-to-look-into-cryotherapy-for-athletes", permanent: true },
      { source: "/the-many-benefits-of-magnesium-oil-when-it-comes-to-health-and-exercise-recovery", destination: "/blog/the-many-benefits-of-magnesium-oil-when-it-comes-to-health-and-exercise-recovery", permanent: true },
      { source: "/the-many-benefits-of-magnesium-oil-when-it-comes-to-health-and-exercise-recovery/", destination: "/blog/the-many-benefits-of-magnesium-oil-when-it-comes-to-health-and-exercise-recovery", permanent: true },
      { source: "/himalayan-salt-room-2", destination: "/blog/himalayan-salt-room-2", permanent: true },
      { source: "/himalayan-salt-room-2/", destination: "/blog/himalayan-salt-room-2", permanent: true },
      { source: "/localised-cyro", destination: "/blog/localised-cyro", permanent: true },
      { source: "/localised-cyro/", destination: "/blog/localised-cyro", permanent: true },
      { source: "/spray-tanning", destination: "/blog/spray-tanning", permanent: true },
      { source: "/spray-tanning/", destination: "/blog/spray-tanning", permanent: true },
      { source: "/cryosuana", destination: "/blog/cryosuana", permanent: true },
      { source: "/cryosuana/", destination: "/blog/cryosuana", permanent: true },
      { source: "/infrared", destination: "/blog/infrared", permanent: true },
      { source: "/infrared/", destination: "/blog/infrared", permanent: true },
      { source: "/michael-henderson", destination: "/blog/michael-henderson", permanent: true },
      { source: "/michael-henderson/", destination: "/blog/michael-henderson", permanent: true },
      { source: "/janey-d", destination: "/blog/janey-d", permanent: true },
      { source: "/janey-d/", destination: "/blog/janey-d", permanent: true },
      { source: "/monica-koudsy", destination: "/blog/monica-koudsy", permanent: true },
      { source: "/monica-koudsy/", destination: "/blog/monica-koudsy", permanent: true },
      { source: "/jean-flamard", destination: "/blog/jean-flamard", permanent: true },
      { source: "/jean-flamard/", destination: "/blog/jean-flamard", permanent: true },
      { source: "/bernadette-vinci", destination: "/blog/bernadette-vinci", permanent: true },
      { source: "/bernadette-vinci/", destination: "/blog/bernadette-vinci", permanent: true },
      { source: "/nikki-phillips", destination: "/blog/nikki-phillips", permanent: true },
      { source: "/nikki-phillips/", destination: "/blog/nikki-phillips", permanent: true },
      { source: "/maya-livneh", destination: "/blog/maya-livneh", permanent: true },
      { source: "/maya-livneh/", destination: "/blog/maya-livneh", permanent: true },
      { source: "/keira-rumble", destination: "/blog/keira-rumble", permanent: true },
      { source: "/keira-rumble/", destination: "/blog/keira-rumble", permanent: true },
    ];
  },
};

export default withPayload(nextConfig);
