/**
 * Blog post slugs from cryospaclinics.com.au (post-sitemap), excluding testimonial/review
 * author pages (e.g. michael-henderson, janey-d) which were incorrectly in the post sitemap.
 * Old URLs for excluded slugs still redirect to /blog/:slug via next.config; no doc is created.
 */
export const BLOG_POST_SLUGS = [
  "unveiling-the-healing-power-of-infrared-saunas-in-sydney",
  "5-tips-to-enhance-your-infrared-sauna-session",
  "what-happens-after-whole-body-cryotherapy",
  "how-infrared-saunas-can-boost-your-immune-system",
  "how-regular-sauna-use-can-help-you-live-longer",
  "does-salt-room-therapy-help-with-acne",
  "red-light-therapy-effectiveness-for-skin-care",
  "vasoconstriction-and-vasodilation-explained",
  "the-paleo-diet-fad-or-friend",
  "how-important-is-sleep-really-when-it-comes-to-living-a-strong-and-balanced-life-and-how-can-cryotherapy-in-australia-help",
  "contrast-therapy-what-is-it-and-why-its-beneficial",
  "salt-therapy-everything-you-need-to-know",
  "how-do-normatec-compression-boots-work-for-recovery",
  "5-ice-bath-benefits-for-health-wellness-and-recovery",
  "is-an-infrared-sauna-better-than-a-regular-sauna",
  "how-salt-therapy-can-help-with-acne",
  "hot-cold-salty-a-visit-to-cryospa-2",
  "vitamin-iv",
  "what-is-red-light-therapy",
  "infrared-saunas-how-hot-do-they-really-get",
  "can-cryotherapy-help-you-lose-weight",
  "how-normatec-compression-therapy-can-help-you",
  "how-infrared-sauna-use-can-help-depression-and-anxiety",
  "suffering-from-acne-heres-how-our-salt-room-can-help",
  "pain-management-here-are-4-ways-we-can-help",
  "vitamin-d-deficiency-what-causes-it-and-how-to-prevent-it",
  "what-causes-inflammation-and-how-can-i-prevent-it",
  "cryotherapy-and-athletes-the-perfect-match",
  "are-hot-baths-beneficial",
  "are-cold-showers-beneficial",
  "chromotherapy-what-is-it-and-how-can-it-help",
  "what-are-the-benefits-of-salt-room-therapy",
  "how-white-blood-cells-impact-immune-system",
  "the-science-behind-the-ketogenic-diet-and-why-it-may-be-beneficial-for-you",
  "why-you-need-to-add-bentonite-clay-to-your-wellness-routine",
  "chroma",
  "whole-body-the-importance-of-sleep-and-steps-you-can-take-to-increase-the-quality-of-your-shut-eye",
  "how-regular-sauna-usage-may-aid-in-reducing-the-risk-of-a-cardiac-event",
  "how-the-wim-hof-method-can-help-prepare-you-for-a-cryotherapy-chamber",
  "how-to-know-when-it-may-be-time-to-look-into-cryotherapy-for-athletes",
  "the-many-benefits-of-magnesium-oil-when-it-comes-to-health-and-exercise-recovery",
  "himalayan-salt-room-2",
  "localised-cyro",
  "spray-tanning",
  "cryosuana",
  "infrared",
] as const;

/** Slugs that are testimonial/review author pages, not blog posts. Redirects stay in next.config. */
export const TESTIMONIAL_AUTHOR_SLUGS = [
  "michael-henderson",
  "janey-d",
  "monica-koudsy",
  "jean-flamard",
  "bernadette-vinci",
  "nikki-phillips",
  "maya-livneh",
  "keira-rumble",
] as const;
